<?php
/**
 * WordPress-safe encryption utilities.
 *
 * Runtime exceptions are _not_ translated to allow this class to be used whenever needed.
 *
 * @package OneUpdate
 */

declare( strict_types = 1 );

namespace OneUpdate;

/**
 * Class - Encryptor
 */
final class Encryptor {
	/**
	 * The salt to use.
	 *
	 * @var string
	 */
	private static string $salt = 'secure_auth';

	/**
	 * Length of the initialization vector when using AES-GCM.
	 *
	 * @var int
	 */
	private const IV_LENGTH = 12;

	/**
	 * Length of the authentication tag generated by AES-GCM.
	 *
	 * @var int
	 */
	private const TAG_LENGTH = 16;

	/**
	 * Encrypts a value using WordPress's built-in encryption.
	 *
	 * @param string $value The value to encrypt.
	 *
	 * @return string The encrypted value.
	 *
	 * @throws \RuntimeException When dependencies are missing or encryption fails.
	 */
	public static function encrypt( string $value ): string|bool {
		$key = self::derive_key();
		$iv  = random_bytes( self::IV_LENGTH );

		$tag        = '';
		$ciphertext = openssl_encrypt( $value, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag );
		if ( false === $ciphertext ) {
			return false;
		}

		return base64_encode( $iv . $tag . $ciphertext );
	}

	/**
	 * Decrypts a value using WordPress's built-in encryption.
	 *
	 * @param string $value The value to decrypt.
	 *
	 * @return string The decrypted value.
	 *
	 * @throws \RuntimeException When dependencies are missing or the payload is invalid.
	 */
	public static function decrypt( string $value ): string|bool {
		$decoded = base64_decode( $value, true );
		if ( false === $decoded || strlen( $decoded ) < self::IV_LENGTH + self::TAG_LENGTH ) {
			return false;
		}

		$key        = self::derive_key();
		$iv         = substr( $decoded, 0, self::IV_LENGTH );
		$tag        = substr( $decoded, self::IV_LENGTH, self::TAG_LENGTH );
		$ciphertext = substr( $decoded, self::IV_LENGTH + self::TAG_LENGTH );

		$plaintext = openssl_decrypt( $ciphertext, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag );
		if ( false === $plaintext ) {
			return false;
		}

		return $plaintext;
	}

	/**
	 * Derive a consistent 256-bit key from the WordPress salt.
	 */
	private static function derive_key(): string {
		static $key = null;

		if ( null === $key ) {
			$key_material = wp_salt( self::$salt );
			$key          = hash( 'sha256', $key_material, true );
		}

		return $key;
	}
}
