name: Inspections
on: pull_request

jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@master
      env:
        SKIP_FOLDERS: "tests,.github,languages,assets,bin,actions,docs"
        GH_BOT_TOKEN: ${{ secrets.RTBOT_TOKEN }}
        PHPCS_SNIFFS_EXCLUDE: "WordPress.Files.FileName"
      with:
        args: WordPress,WordPress-Core,WordPress-Docs
